name: ci

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO: ${{ secrets.REPO }}
  OWNER: ${{ secrets.OWNER }}
  TOKEN: ${{ secrets.TOKEN_GIT }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - 
        name: Build and Push the Docker image
        run: |
          docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPO:${{ steps.date.outputs.date }}
          docker push $DOCKERHUB_USERNAME/$REPO:${{ steps.date.outputs.date }}
          echo "::set-output name=digest::$(docker images $DOCKERHUB_USERNAME/$REPO --digests | grep ${{ steps.date.outputs.date }} | awk '{print $3}')"
          echo "::set-output name=commit_sha::$(git rev-parse --short HEAD)"
      -
        name: Test Variables
        run: |
          echo  ${{ steps.digest.outputs.digest }}
          echo  ${{ steps.digest.outputs.commit_sha }}
      - 
        name: Send Keptn Event
        run: |
          send_keptn_payload="$(curl -H "Accept: application/vnd.github+json" -H "Authorization: token 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" https://api.github.com/repos/codeWithUtkarsh/web-app-ui/commits/$commit | jq -r '{"commit":., "docker_digest":"sha256:bfe4fb2b247328666b99a4b4d02efba9151c43782eda347a55e64ff42db57e7c"}')"
          # echo "$send_keptn_payload"

          generate_keptn_data()
          {
            cat <<EOF
          {
            "shkeptncontext": "string",
            "triggeredid": "string",
            "gitcommitid": "string",
            "shkeptnversion": "string",
            "specversion": "string",
            "contenttype": "string",
            "data": $send_keptn_payload,
            "id": "string",
            "time": "2022-08-25T05:17:32.420Z",
            "type": "string",
            "extensions": {},
            "source": "string"
          }
          EOF
          }

          echo "$(curl -X 'POST' \
            'http://20.22.144.90.nip.io/api/v1/event' \
            -H 'accept: application/json' \
            -H 'x-token: 9mP2nHY39hMSHIBDmg1U9ZcUJ0u6vaefQ3JJrOZ2ipnsf' \
            -H 'Content-Type: application/json' \
            -d "$(generate_keptn_data)")"
          
