name: ci

on:
  push:
    branches:
      - 'main'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO: ${{ secrets.REPO }}
  OWNER: ${{ github.repository_owner }}
  TOKEN: ${{ github.token }}
  KEPTN_TOKEN: ${{ secrets.KEPTN_TOKEN }}
  KEPTN_API_URL: ${{ secrets.KEPTN_API_URL }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - 
        name: Build and Push the Docker image
        id: docker
        run: |
          docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPO:${{ steps.date.outputs.date }}
          docker push $DOCKERHUB_USERNAME/$REPO:${{ steps.date.outputs.date }}
          echo "::set-output name=digest::$(docker images $DOCKERHUB_USERNAME/$REPO --digests | grep ${{ steps.date.outputs.date }} | awk '{print $3}')"
          echo "::set-output name=commit_sha::$(git rev-parse --short HEAD)"
      -
        name: Test Variables
        run: |
          echo  ${{ steps.docker.outputs.digest }}
          echo  ${{ steps.docker.outputs.commit_sha }}
      - 
        name: Send Keptn Event
        run: |
          APP_COMMIT_DETAILS="$(curl -H "Accept: application/vnd.github+json" -H "Authorization: token $TOKEN" https://api.github.com/repos/$OWNER/$REPO/commits/${{ steps.docker.outputs.commit_sha }} | jq -r '{"commit":., "docker_digest":"${{ steps.docker.outputs.digest }}"}')"
          echo "$APP_COMMIT_DETAILS"

          generate_application_data()
          {
            cat <<EOF
          {
              "data": {
                "configurationChange": {
                  "values": {
                    "image": "ghcr.io/podtato-head/podtatoserver:v0.1.1"
                  }
                },
                "applicationMeta": $APP_COMMIT_DETAILS
                "deployment": {
                  "deploymentstrategy": "blue_green_service"
                },
                "message": "",
                "project": "ms1",
                "result": "",
                "service": "helloservice",
                "stage": "hardening",
                "status": ""
              },
              "source": "gh",
              "specversion": "1.0",
              "type": "sh.keptn.event.hardening.delivery.deployment",
              "shkeptnspecversion": "0.2.1"
            }
          EOF
          }

          echo "$(generate_application_data)"
          echo "$(curl -X 'POST' \
            'http://20.22.144.90.nip.io/api/v1/event' \
            -H 'accept: application/json' \
            -H "x-token: $KEPTN_TOKEN" \
            -H 'Content-Type: application/json' \
            -d "$(generate_application_data)")"
